@Api_HostAddress = http://localhost:5080

###

POST http://localhost:5080/tpt/departments/
Content-Type: application/json

{
  "name": "Cardiology",
  "hospitalId": 1,
  "phoneNumber": {
    "number": "+1-555-123-4567",
    "label": "mobile"
  },
  "email": {
    "value": "cardio@test.com"
  }
}