@Api_HostAddress = http://localhost:5080

###

POST http://localhost:5080/tph/departments/
Content-Type: application/json

{
  "name": "Cardiology",
  "hospitalId": 3,
  "phoneNumber": {
    "number": "5559562298",
    "label": "Reception"
  },
  "email": {
    "value": "cardiology@cityhospital.com"
  }
}