// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.TPH
{
    [DbContext(typeof(HospitalTphDbContext))]
    [Migration("20260416153231_InitialTphMigration")]
    partial class InitialTphMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TPH.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("Name", "HospitalId")
                        .IsUnique();

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TPH.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("_address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Address");

                    b.Property<DateTimeOffset>("_builtDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("BuiltDate");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Hospital", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TPH.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PersonnelType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("_shiftEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("ShiftEnd");

                    b.Property<DateTime>("_shiftStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("ShiftStart");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Personnel", (string)null);

                    b.HasDiscriminator<string>("PersonnelType").HasValue("Personnel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.TPH.Doctor", b =>
                {
                    b.HasBaseType("Domain.Entities.TPH.Personnel");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Janitor", b =>
                {
                    b.HasBaseType("Domain.Entities.TPH.Personnel");

                    b.Property<string>("AssignedZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("BiohazardCertified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SecurityClearanceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("Janitor");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Nurse", b =>
                {
                    b.HasBaseType("Domain.Entities.TPH.Personnel");

                    b.Property<string>("AssignedWard")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CertificationLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsHeadNurse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue("Nurse");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Receptionist", b =>
                {
                    b.HasBaseType("Domain.Entities.TPH.Personnel");

                    b.Property<string>("DeskLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("HandlesInsuranceBilling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasDiscriminator().HasValue("Receptionist");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Technician", b =>
                {
                    b.HasBaseType("Domain.Entities.TPH.Personnel");

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EquipmentSpecialty")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TechnicalCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue("Technician");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Department", b =>
                {
                    b.HasOne("Domain.Entities.TPH.Hospital", "Hospital")
                        .WithMany("Departments")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.ValueObjects.EmailAddress", "EmailAddresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DepartmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.HasKey("Id");

                            b1.HasIndex("DepartmentId");

                            b1.HasIndex("DepartmentId", "Value")
                                .IsUnique();

                            b1.ToTable("DepartmentEmailAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.OwnsMany("Domain.ValueObjects.PhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DepartmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("DepartmentId");

                            b1.HasIndex("DepartmentId", "Number", "Label")
                                .IsUnique();

                            b1.ToTable("DepartmentPhoneNumbers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("EmailAddresses");

                    b.Navigation("Hospital");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Hospital", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.EmailAddress", "MainEmailAddress", b1 =>
                        {
                            b1.Property<int>("HospitalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("MainEmailAddress");

                            b1.HasKey("HospitalId");

                            b1.ToTable("Hospital");

                            b1.WithOwner()
                                .HasForeignKey("HospitalId");
                        });

                    b.OwnsOne("Domain.ValueObjects.PhoneNumber", "MainPhoneNumber", b1 =>
                        {
                            b1.Property<int>("HospitalId")
                                .HasColumnType("int");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("MainPhoneLabel");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("MainPhoneNumber");

                            b1.HasKey("HospitalId");

                            b1.ToTable("Hospital");

                            b1.WithOwner()
                                .HasForeignKey("HospitalId");
                        });

                    b.Navigation("MainEmailAddress")
                        .IsRequired();

                    b.Navigation("MainPhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPH.Personnel", b =>
                {
                    b.HasOne("Domain.Entities.TPH.Department", "Department")
                        .WithMany("Personnel")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.EmailAddress", "EmailAddress", b1 =>
                        {
                            b1.Property<int>("PersonnelId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.HasKey("PersonnelId");

                            b1.ToTable("Personnel");

                            b1.WithOwner()
                                .HasForeignKey("PersonnelId");
                        });

                    b.OwnsOne("Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("PersonnelId")
                                .HasColumnType("int");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("PersonnelId");

                            b1.ToTable("Personnel");

                            b1.WithOwner()
                                .HasForeignKey("PersonnelId");
                        });

                    b.Navigation("Department");

                    b.Navigation("EmailAddress")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPH.Receptionist", b =>
                {
                    b.OwnsMany("Domain.ValueObjects.ReceptionistLanguage", "KnownLanguages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Proficiency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("ReceptionistId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ReceptionistId");

                            b1.ToTable("ReceptionistLanguages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReceptionistId");
                        });

                    b.Navigation("KnownLanguages");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Department", b =>
                {
                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("Domain.Entities.TPH.Hospital", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
