// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.TPT
{
    [DbContext(typeof(HospitalTptDbContext))]
    [Migration("20260424175946_AudibleUpdatedAndCreatedByToNullable")]
    partial class AudibleUpdatedAndCreatedByToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TPT.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("Name", "HospitalId")
                        .IsUnique();

                    b.ToTable("Departments", "Staff");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("HospitalAddress");

                    b.Property<DateTimeOffset>("BuiltDate")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasColumnName("HospitalBuiltDate");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Hospital", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<byte>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("Gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ShiftEnd")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("ShiftEnd");

                    b.Property<DateTime>("ShiftStart")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("ShiftStart");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Name", "DepartmentId");

                    b.ToTable("Personnel", "Staff", t =>
                        {
                            t.HasComment("Primary table for TPT hierarchy of all staff members");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.TPT.Doctor", b =>
                {
                    b.HasBaseType("Domain.Entities.TPT.Personnel");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LicenseNumber");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Specialization");

                    b.ToTable("Doctors", "Staff");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Janitor", b =>
                {
                    b.HasBaseType("Domain.Entities.TPT.Personnel");

                    b.Property<string>("AssignedZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AssignedZone");

                    b.Property<bool>("BiohazardCertified")
                        .HasColumnType("bit")
                        .HasColumnName("BiohazardCertified");

                    b.Property<string>("SecurityClearanceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SecurityClearanceLevel");

                    b.ToTable("Janitors", "Staff");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Nurse", b =>
                {
                    b.HasBaseType("Domain.Entities.TPT.Personnel");

                    b.Property<string>("AssignedWard")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("AssignedWard");

                    b.Property<string>("CertificationLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CertificationLevel");

                    b.Property<bool>("IsHeadNurse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IsHeadNurse")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ShiftType");

                    b.ToTable("Nurses", "Staff");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Receptionist", b =>
                {
                    b.HasBaseType("Domain.Entities.TPT.Personnel");

                    b.Property<string>("DeskLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("DeskLocation");

                    b.Property<bool>("HandlesInsuranceBilling")
                        .HasColumnType("bit")
                        .HasColumnName("HandlesInsuranceBilling");

                    b.ToTable("Receptionists", "Staff");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Technician", b =>
                {
                    b.HasBaseType("Domain.Entities.TPT.Personnel");

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("CertificationNumber");

                    b.Property<string>("EquipmentSpecialty")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("EquipmentSpecialty");

                    b.Property<string>("TechnicalCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TechnicalCategory");

                    b.ToTable("Technicians", "Staff");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Department", b =>
                {
                    b.HasOne("Domain.Entities.TPT.Hospital", "Hospital")
                        .WithMany("Departments")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.ValueObjects.EmailAddress", "EmailAddresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DepartmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.HasKey("Id", "DepartmentId");

                            b1.HasIndex("DepartmentId");

                            b1.ToTable("DepartmentEmailAddresses", "Staff");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.OwnsMany("Domain.ValueObjects.PhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DepartmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("Id", "DepartmentId");

                            b1.HasIndex("DepartmentId");

                            b1.ToTable("DepartmentPhoneNumbers", "Staff");

                            b1.WithOwner()
                                .HasForeignKey("DepartmentId");
                        });

                    b.Navigation("EmailAddresses");

                    b.Navigation("Hospital");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Hospital", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.EmailAddress", "MainEmailAddress", b1 =>
                        {
                            b1.Property<int>("HospitalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("MainEmailAddress");

                            b1.HasKey("HospitalId");

                            b1.ToTable("HospitalEmailAddress", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("HospitalId");
                        });

                    b.OwnsOne("Domain.ValueObjects.PhoneNumber", "MainPhoneNumber", b1 =>
                        {
                            b1.Property<int>("HospitalId")
                                .HasColumnType("int");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("MainPhoneLabel");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("MainPhoneNumber");

                            b1.HasKey("HospitalId");

                            b1.ToTable("HospitalPhoneNumber", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("HospitalId");
                        });

                    b.Navigation("MainEmailAddress")
                        .IsRequired();

                    b.Navigation("MainPhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPT.Personnel", b =>
                {
                    b.HasOne("Domain.Entities.TPT.Department", "Department")
                        .WithMany("Personnel")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.EmailAddress", "EmailAddress", b1 =>
                        {
                            b1.Property<int>("PersonnelId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("EmailAddress");

                            b1.HasKey("PersonnelId");

                            b1.ToTable("PersonnelEmailAddress", "Staff");

                            b1.WithOwner()
                                .HasForeignKey("PersonnelId");
                        });

                    b.OwnsOne("Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("PersonnelId")
                                .HasColumnType("int");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("PhoneLabel");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("PersonnelId");

                            b1.ToTable("PersonnelPhone", "Staff");

                            b1.WithOwner()
                                .HasForeignKey("PersonnelId");
                        });

                    b.Navigation("Department");

                    b.Navigation("EmailAddress")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPT.Doctor", b =>
                {
                    b.HasOne("Domain.Entities.TPT.Personnel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.TPT.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPT.Janitor", b =>
                {
                    b.HasOne("Domain.Entities.TPT.Personnel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.TPT.Janitor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPT.Nurse", b =>
                {
                    b.HasOne("Domain.Entities.TPT.Personnel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.TPT.Nurse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPT.Receptionist", b =>
                {
                    b.HasOne("Domain.Entities.TPT.Personnel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.TPT.Receptionist", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.ValueObjects.ReceptionistLanguage", "KnownLanguages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("ReceptionistId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LanguageName");

                            b1.Property<string>("Proficiency")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LanguageProficiency");

                            b1.HasKey("Id", "ReceptionistId");

                            b1.HasIndex("ReceptionistId");

                            b1.ToTable("ReceptionistLanguages", "Staff");

                            b1.WithOwner()
                                .HasForeignKey("ReceptionistId");
                        });

                    b.Navigation("KnownLanguages");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Technician", b =>
                {
                    b.HasOne("Domain.Entities.TPT.Personnel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.TPT.Technician", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TPT.Department", b =>
                {
                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("Domain.Entities.TPT.Hospital", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
